# These two functions allow calculation of the inverse
# of a matrix with caching (also called memoization).
# Results are stored, and if the same argument is entered
# again, the previously calculated result is returned.
# According to the specifications, it is assumed that the
# matrix entered is always invertible, so no code to
# detect erroneous arguments is included.

# This function accepts a matrix and returns a list of
# functions that cache and retrieve the data. The matrix
# entered must be a square matrix with non-zero determinant,
# which can be checked with the det() function in R.

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) m <<- solve
  getinverse <- function() m
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}


# This function accepts the list generated by the function
# makeCacheMatrix and returns the inverse of the matrix
# entered as the argument to makeCacheMatrix.

cacheSolve <- function(x, ...) {
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
}
